// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFMC2Q2UwoDt0U0dFPPmGgqeFzPfJMJSo',
    appId: '1:287531344986:web:8a85ab7dcca415d031e463',
    messagingSenderId: '287531344986',
    projectId: 'inc22-1ac78',
    authDomain: 'inc22-1ac78.firebaseapp.com',
    storageBucket: 'inc22-1ac78.appspot.com',
    measurementId: 'G-4XTVL041XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjQucYs_299mGFctm86n-qSSwTFzLRzyY',
    appId: '1:287531344986:android:a166f41ee4967d5e31e463',
    messagingSenderId: '287531344986',
    projectId: 'inc22-1ac78',
    storageBucket: 'inc22-1ac78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2YYKpoj3zyXRmfAh4tEntp4GGIB9q6Wk',
    appId: '1:287531344986:ios:c42b3b7ef20d310631e463',
    messagingSenderId: '287531344986',
    projectId: 'inc22-1ac78',
    storageBucket: 'inc22-1ac78.appspot.com',
    iosClientId:
        '287531344986-hlrblue2u78mda3jtrgu2m0am09qfr9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.inc22',
  );
}
